INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (2,'Arrivano gli americani','Compra giocatori di prospettiva per far plusvlenze');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (3,'Arrivano gli sceicchi','Spendi tutto il budget per vincere un trofeo');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (4,'Presidente patriottico','Schierare in campo almeno 6 giocatori della propria nazione di appartenenza');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (5,'Operazione rifondazione','Rifondare la squadra per imposizione societaria');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (7,'Operazione giovanili','Schierare nella formazione almeno 3 giovani');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (8,'Io sono il Condor!','Acquistare parametri 0 o vecchie glorie');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (9,'Non spendo soldi per gli acquisti','Acquista giocatori tramite svincolati prestiti o scambi');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (10,'Rispetta il passato','Acquista giocatori solo provenienti da nazioni a cui la societa'' e'' legata');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (12,'Io sono Paratici','Acquista giocatori di prospettiva o dalle giovanili e rivendili per plusvalenze');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (13,'Accetta tutte le offerte','Accetta ogni offerta che arriva');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (14,'Operazione giovani','Acquista solo giocatori al di sotto dei 24 anni');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (15,'Occhio alla perestrojka','Acquista solo giocatori dell''est Europa');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (17,'Ti presento Giginho','Acquista solo giocatori sudamericani');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (18,'Sono er figlio de Gaucci','Acquista giocatori o manda osservatori in paesi esotici');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (19,'Suolo natio','Acquista solo giocatori della stessa nazione del campionato di appartenenza');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (20,'Operazione RSA','Eta media squadra sopra i 30 anni');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (21,'Fallimento Sponsor principale','Non spendere il budget trasferimenti fino inizio stagione successica');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (22,'Cambiamento regole permesso di lavoro','Vendi tutti i giocatori non appartenenti all''area geografica di appartenenza');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (23,'Illecito sportivo mercato giovanili','Vendi il tuo miglior giocatore under 25');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (24,'Mal D''Africa','Invia osservatore 9 mesi in Africa e acquista un giocatore africano');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (25,'Investitori perdono interesse nel team','Per la stagione successiva vendi i giocatori con contratti piÃ¹ elevati');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (26,'Qui comanda il presidente','Obbligo di giocare con il modulo imposto dal presidente');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (27,'Trovati un altra squadra','Il presidente non rinnoverÃ  il tuo contratto e');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (28,'Siamo affiliati!','Prendi in prestito 3 giocatori da squadre con overall piÃ¹ elevato');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (29,'Licenzia tutto lo staff','Cambia tutti gli scout della squadra');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (30,'Espansione mercato asiatico','Acquista giocatori di nazionalita asiatica');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (31,'I love the Commonwealth','Acquista giocatori nordamericani australiani o neozelandesi');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (32,'Non siamo ambiziosi!','Acquista due giocatori di fama internazionale');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (33,'Tengo Saudade','Vendi un giocatore sudamericano');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (34,'Se so bevuti il presidente','Vendi i giocatori piÃ¹ forti per abbassare di tre punti l''overall della squadra');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (35,'Rivolta tifosi!','Per calmare la piazza acquista un giocatore con overall piÃ¹ alto della squadra');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (36,'Voglio solo profitti!','Vendi in ogni finestra di mercato un giocatore per avere un profitto');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (37,'Rispettiamo UE','Compra solo giocatori dell''UE');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (38,'Dio salvi la regina','Acquista solo giocatori provenienti dalla Gran Bretagna');
INSERT INTO TRANSFERMARKET_ISSUE(id,issue_type,issue_description) VALUES (39,'Sono figlio di Attila Flagello di Dio!','Acquista solo giocatori scandinavi');

INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (1,'RAFFREDDORE','3 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (2,'INFLUENZA','7 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (3,'VIRUS','14 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (4,'COVID-19','21 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (6,'GRAVE INFEZIONE VIRALE','1 MESE FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (7,'CAVIGLIA SLOGATA','20 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (8,'STIRAMENTO ALLA CAVIGLIA','14 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (9,'CONTUSIONE AL PIEDE','15 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (11,'STIRAMENTO GINOCCHIO','10 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (12,'DISTORSIONE GINOCCHIO','30 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (13,'INFIAMMAZIONE ROTULA','20 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (14,'STRAPPO LEGAMENTO GINOCCHIO','60 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (16,'STIRAMENTO BICIPITE FEMORALE','7 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (17,'CONTUSIONE COSCIA','5 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (18,'STIRAMENTO MUSCOLO COSCIA','14 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (19,'STIRAMENTO INGUINE','14 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (21,'STRAPPO MUSCOLO INGUINE','25 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (22,'CONTUSIONE COSTOLA','3 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (23,'STIRAMENTO ALLA SCHIENA','14 GIORNI FUORI PER INFORTUNEO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (24,'SCANDALO SOCIAL','15 GIORNI PER COMPORTAMENTO SCORRETTO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (26,'CREDO IN TE','SCHIERA TITOLARE UNO DEI PEGGIORI GIOCATORI DELLA ROSA');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (27,'RITARDO ALLENAMENTO','7 GIORNI FUORI PER COMPORTAMENTO NON PROFESSIONALE');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (28,'BERE AL PARCO','LICENZIA IL GIOCATORE PIU'' FORTE E I DUE PIU'' DEBOLI DEL VIVAIO');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (29,'QUANDO TOCCA A NOI','SCHIERA LE RISERVE PER LA PROSSIMA PARTITA');
INSERT INTO PLAYER_ISSUE(id,issue_type,issue_description) VALUES (31,'SQUALIFICA PER INGIURIA ARBITRO','IL GIOCATORE E'' SQUALIFICATO PER 2 PARTITE PER OFFESE ALL''ARBITRO');

INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (1,'DEBITO SOCIETA 10%','RIDUZIONE BUDGET 10%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (2,'DEBITO SOCIETA 30%','RIDUZIONE BUDGET 30%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (3,'DEBITO SOCIETA 50%','RIDUZIONE BUDGET 50%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (4,'DEBITO SOCIETA 70%','RIDUZIONE BUDGET 70%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (6,'DEBITO SOCIETA 100%','BANCAROTTA');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (7,'BLOCCO MERCATO','BLOCCO MERCATO');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (8,'CAMBIO SOCIETA AUMENTO 10%','AUMENTO BUDGET 10%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (9,'CAMBIO SOCIETA AUMENTO 30%','AUMENTO BUDGET 30%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (11,'CAMBIO SOCIETA AUMENTO 50%','AUMENTO BUDGET 50%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (12,'CAMBIO SOCIETA AUMENTO 70%','AUMENTO BUDGET 70%');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (13,'CAMBIO SOCIETARIO FONDO ARABO/CINESE','AUMENTO BUDGET 250 MILIONI EURO');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (14,'PRESIDENTE PATRIOTTICO','SCHIERARE IN CAMPO ALMENO 6 GIOCATORI DELLA PROPRIA NAZIONE DI APPARTENENZA');
INSERT INTO TEAM_ISSUE(id,issue_type,issue_description) VALUES (16,'COSTRUZIONE NUOVO STADIO','RIDUZIONE 50% DEL BUDGET TRASFERIMENTI PER COSTUZIONE NUOVO STADIO');
